//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaderboardDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Leaderboard { get; set; }
        public int Rating { get; set; }
    }
}
